### ISSUE TITLE
A typo in the Instruction part

### ISSUE THREAD

**Issue by Doveyang** [JacksonWuxs/datapy#4]
DataPy.dataset(addr='data.csv', title=True, split='AUTO', db=None, name=Data, firstline=1, miss_value=None)

Should be

DataPy.dataset(addr='data.csv', title=True, split='AUTO', db=None, name='Data', firstline=1, miss_value=None)

**Comment by JacksonWuxs** [comment]
Thanks for you correcting suggestion!
